### ISSUE TITLE
Kanban setup

### ISSUE THREAD

**Issue by M0rrighan** [tmampa/space-x#25]
Link to project: https://github.com/tmampa/space-x/projects/1
Note: a group of two Micronauts.

**Comment by elyor-doniyorov** [comment]
Hi @M0rrighan and @tmampa, 

Your Kanban Board milestone is complete!  There is nothing else to say other than... it's time to start working on it :shipit: 
Congratulations! 🎉 
# STATUS APPROVED ✅ 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
